/*
 * generated by Xtext
 */
package org;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class AiocRuntimeModule extends org.AbstractAiocRuntimeModule {

}
