/*
* generated by Xtext
*/
package org;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class AiocStandaloneSetup extends AiocStandaloneSetupGenerated{

	public static void doSetup() {
		new AiocStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

