/*
 * generated by Xtext
 */
package org.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class AiocUiModule extends org.ui.AbstractAiocUiModule {
	public AiocUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
